include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_null_checks_in_equality_operators
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_unnecessary_containers
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_null_aware_operators
    - prefer_single_quotes
    - require_trailing_commas