// Mocks generated by Mockito 5.4.6 from annotations
// in cribe/test/ui/podcasts/widgets/episode_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i9;

import 'package:cribe/core/logger/logger_mixins.dart' as _i3;
import 'package:cribe/data/services/transcription_service.dart' as _i8;
import 'package:cribe/domain/models/podcast.dart' as _i2;
import 'package:cribe/domain/models/transcript.dart' as _i5;
import 'package:cribe/ui/podcasts/view_models/episode_detail_view_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEpisode_0 extends _i1.SmartFake implements _i2.Episode {
  _FakeEpisode_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContextualLogger_1 extends _i1.SmartFake
    implements _i3.ContextualLogger {
  _FakeContextualLogger_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EpisodeDetailViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockEpisodeDetailViewModel extends _i1.Mock
    implements _i4.EpisodeDetailViewModel {
  MockEpisodeDetailViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Episode get episode => (super.noSuchMethod(
        Invocation.getter(#episode),
        returnValue: _FakeEpisode_0(
          this,
          Invocation.getter(#episode),
        ),
      ) as _i2.Episode);

  @override
  List<_i5.TranscriptChunk> get chunks => (super.noSuchMethod(
        Invocation.getter(#chunks),
        returnValue: <_i5.TranscriptChunk>[],
      ) as List<_i5.TranscriptChunk>);

  @override
  Map<int, String> get speakers => (super.noSuchMethod(
        Invocation.getter(#speakers),
        returnValue: <int, String>{},
      ) as Map<int, String>);

  @override
  int get currentTranscriptChunkPosition => (super.noSuchMethod(
        Invocation.getter(#currentTranscriptChunkPosition),
        returnValue: 0,
      ) as int);

  @override
  double get currentAudioPosition => (super.noSuchMethod(
        Invocation.getter(#currentAudioPosition),
        returnValue: 0.0,
      ) as double);

  @override
  double get transcriptSyncOffset => (super.noSuchMethod(
        Invocation.getter(#transcriptSyncOffset),
        returnValue: 0.0,
      ) as double);

  @override
  bool get transcriptCompleted => (super.noSuchMethod(
        Invocation.getter(#transcriptCompleted),
        returnValue: false,
      ) as bool);

  @override
  bool get isStreaming => (super.noSuchMethod(
        Invocation.getter(#isStreaming),
        returnValue: false,
      ) as bool);

  @override
  List<_i5.SpeakerTurn> get speakerTurns => (super.noSuchMethod(
        Invocation.getter(#speakerTurns),
        returnValue: <_i5.SpeakerTurn>[],
      ) as List<_i5.SpeakerTurn>);

  @override
  double get playbackProgress => (super.noSuchMethod(
        Invocation.getter(#playbackProgress),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  bool get isCompleted => (super.noSuchMethod(
        Invocation.getter(#isCompleted),
        returnValue: false,
      ) as bool);

  @override
  bool get isBuffering => (super.noSuchMethod(
        Invocation.getter(#isBuffering),
        returnValue: false,
      ) as bool);

  @override
  String get duration => (super.noSuchMethod(
        Invocation.getter(#duration),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#duration),
        ),
      ) as String);

  @override
  String get datePublished => (super.noSuchMethod(
        Invocation.getter(#datePublished),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#datePublished),
        ),
      ) as String);

  @override
  String get elapsedTime => (super.noSuchMethod(
        Invocation.getter(#elapsedTime),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#elapsedTime),
        ),
      ) as String);

  @override
  String get remainingTime => (super.noSuchMethod(
        Invocation.getter(#remainingTime),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#remainingTime),
        ),
      ) as String);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isSuccess => (super.noSuchMethod(
        Invocation.getter(#isSuccess),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.ContextualLogger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeContextualLogger_1(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i3.ContextualLogger);

  @override
  _i7.Future<void> startTranscriptStreamWith(
          _i8.TranscriptionService? service) =>
      (super.noSuchMethod(
        Invocation.method(
          #startTranscriptStreamWith,
          [service],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> stopTranscriptStream() => (super.noSuchMethod(
        Invocation.method(
          #stopTranscriptStream,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void togglePlayPause() => super.noSuchMethod(
        Invocation.method(
          #togglePlayPause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void seekTo(double? progress) => super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [progress],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLoading(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setLoading,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setError(String? value) => super.noSuchMethod(
        Invocation.method(
          #setError,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSuccess(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setSuccess,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
