// Mocks generated by Mockito 5.4.6 from annotations
// in cribe/test/ui/podcasts/widgets/episode_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i5;

import 'package:cribe/core/logger/logger_mixins.dart' as _i2;
import 'package:cribe/ui/podcasts/view_models/episode_detail_view_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContextualLogger_0 extends _i1.SmartFake
    implements _i2.ContextualLogger {
  _FakeContextualLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EpisodeDetailViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockEpisodeDetailViewModel extends _i1.Mock
    implements _i3.EpisodeDetailViewModel {
  MockEpisodeDetailViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get playbackProgress => (super.noSuchMethod(
        Invocation.getter(#playbackProgress),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i2.ContextualLogger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeContextualLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.ContextualLogger);

  @override
  void togglePlayPause() => super.noSuchMethod(
        Invocation.method(
          #togglePlayPause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void seekTo(double? progress) => super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [progress],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String formatDuration(int? seconds) => (super.noSuchMethod(
        Invocation.method(
          #formatDuration,
          [seconds],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #formatDuration,
            [seconds],
          ),
        ),
      ) as String);

  @override
  String formatDate(String? dateString) => (super.noSuchMethod(
        Invocation.method(
          #formatDate,
          [dateString],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #formatDate,
            [dateString],
          ),
        ),
      ) as String);

  @override
  String getCurrentTime() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentTime,
          [],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentTime,
            [],
          ),
        ),
      ) as String);

  @override
  String getTotalTime() => (super.noSuchMethod(
        Invocation.method(
          #getTotalTime,
          [],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getTotalTime,
            [],
          ),
        ),
      ) as String);

  @override
  void setLoading(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setLoading,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setError(String? value) => super.noSuchMethod(
        Invocation.method(
          #setError,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
