// Mocks generated by Mockito 5.4.6 from annotations
// in cribe/test/ui/podcasts/widgets/podcast_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cribe/core/logger/logger_mixins.dart' as _i2;
import 'package:cribe/data/repositories/podcasts/podcast_repository.dart'
    as _i4;
import 'package:cribe/domain/models/podcast.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContextualLogger_0 extends _i1.SmartFake
    implements _i2.ContextualLogger {
  _FakeContextualLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePodcast_1 extends _i1.SmartFake implements _i3.Podcast {
  _FakePodcast_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PodcastRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPodcastRepository extends _i1.Mock implements _i4.PodcastRepository {
  MockPodcastRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Podcast> get podcasts => (super.noSuchMethod(
        Invocation.getter(#podcasts),
        returnValue: <_i3.Podcast>[],
      ) as List<_i3.Podcast>);

  @override
  _i2.ContextualLogger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeContextualLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.ContextualLogger);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> getPodcasts() => (super.noSuchMethod(
        Invocation.method(
          #getPodcasts,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Podcast> getPodcastById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getPodcastById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Podcast>.value(_FakePodcast_1(
          this,
          Invocation.method(
            #getPodcastById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Podcast>);

  @override
  _i5.Future<List<_i3.Episode>> getEpisodesByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByPodcastId,
          [podcastId],
        ),
        returnValue: _i5.Future<List<_i3.Episode>>.value(<_i3.Episode>[]),
      ) as _i5.Future<List<_i3.Episode>>);

  @override
  dynamic setPodcasts(List<_i3.Podcast>? podcasts) =>
      super.noSuchMethod(Invocation.method(
        #setPodcasts,
        [podcasts],
      ));
}
