// Mocks generated by Mockito 5.4.6 from annotations
// in cribe/test/ui/settings/widgets/settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i4;
import 'dart:ui' as _i11;

import 'package:cribe/core/constants/feature_flags.dart' as _i10;
import 'package:cribe/core/constants/storage_keys.dart' as _i7;
import 'package:cribe/core/logger/logger_mixins.dart' as _i2;
import 'package:cribe/data/model/auth/login_response.dart' as _i12;
import 'package:cribe/data/providers/feature_flags_provider.dart' as _i9;
import 'package:cribe/data/services/api_service.dart' as _i5;
import 'package:cribe/data/services/storage_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContextualLogger_0 extends _i1.SmartFake
    implements _i2.ContextualLogger {
  _FakeContextualLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageService_1 extends _i1.SmartFake
    implements _i3.StorageService {
  _FakeStorageService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClient_2 extends _i1.SmartFake implements _i4.HttpClient {
  _FakeHttpClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_3<T1> extends _i1.SmartFake
    implements _i5.ApiResponse<T1> {
  _FakeApiResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i3.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ContextualLogger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeContextualLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.ContextualLogger);

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  String getValue(_i7.StorageKey? key) => (super.noSuchMethod(
        Invocation.method(
          #getValue,
          [key],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getValue,
            [key],
          ),
        ),
      ) as String);

  @override
  _i6.Future<String> getSecureValue(_i7.SecureStorageKey? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSecureValue,
          [key],
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getSecureValue,
            [key],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<bool> setSecureValue(
    _i7.SecureStorageKey? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSecureValue,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> setValue(
    _i7.StorageKey? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setValue,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [FeatureFlagsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeatureFlagsProvider extends _i1.Mock
    implements _i9.FeatureFlagsProvider {
  MockFeatureFlagsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i2.ContextualLogger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeContextualLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.ContextualLogger);

  @override
  T getFlag<T>(_i10.FeatureFlagKey? key) => (super.noSuchMethod(
        Invocation.method(
          #getFlag,
          [key],
        ),
        returnValue: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #getFlag,
            [key],
          ),
        ),
      ) as T);

  @override
  void setFlag<T>(
    _i10.FeatureFlagKey? key,
    T? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setFlag,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetToDefaults() => super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getAllFlags() => (super.noSuchMethod(
        Invocation.method(
          #getAllFlags,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.StorageService get storageService => (super.noSuchMethod(
        Invocation.getter(#storageService),
        returnValue: _FakeStorageService_1(
          this,
          Invocation.getter(#storageService),
        ),
      ) as _i3.StorageService);

  @override
  _i4.HttpClient get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeHttpClient_2(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i4.HttpClient);

  @override
  _i2.ContextualLogger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeContextualLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.ContextualLogger);

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  dynamic updateBaseUrl(String? newUrl) => super.noSuchMethod(Invocation.method(
        #updateBaseUrl,
        [newUrl],
      ));

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setTokens(_i12.LoginResponse? tokens) => (super.noSuchMethod(
        Invocation.method(
          #setTokens,
          [tokens],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i5.ApiResponse<T>> get<T>(
    String? path,
    T Function(dynamic)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            path,
            fromJson,
          ],
        ),
        returnValue: _i6.Future<_i5.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #get,
            [
              path,
              fromJson,
            ],
          ),
        )),
      ) as _i6.Future<_i5.ApiResponse<T>>);

  @override
  _i6.Future<_i5.ApiResponse<T>> post<T>(
    String? path,
    T Function(dynamic)? fromJson, {
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            path,
            fromJson,
          ],
          {#body: body},
        ),
        returnValue: _i6.Future<_i5.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #post,
            [
              path,
              fromJson,
            ],
            {#body: body},
          ),
        )),
      ) as _i6.Future<_i5.ApiResponse<T>>);

  @override
  _i6.Future<_i5.ApiResponse<T>> delete<T>(
    String? path,
    T Function(dynamic)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            path,
            fromJson,
          ],
        ),
        returnValue: _i6.Future<_i5.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #delete,
            [
              path,
              fromJson,
            ],
          ),
        )),
      ) as _i6.Future<_i5.ApiResponse<T>>);

  @override
  _i6.Future<_i5.ApiResponse<T>> put<T>(
    String? path,
    T Function(dynamic)? fromJson, {
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            path,
            fromJson,
          ],
          {#body: body},
        ),
        returnValue: _i6.Future<_i5.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #put,
            [
              path,
              fromJson,
            ],
            {#body: body},
          ),
        )),
      ) as _i6.Future<_i5.ApiResponse<T>>);

  @override
  _i6.Future<_i5.ApiResponse<T>> patch<T>(
    String? path,
    T Function(dynamic)? fromJson, {
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [
            path,
            fromJson,
          ],
          {#body: body},
        ),
        returnValue: _i6.Future<_i5.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #patch,
            [
              path,
              fromJson,
            ],
            {#body: body},
          ),
        )),
      ) as _i6.Future<_i5.ApiResponse<T>>);
}
