// Mocks generated by Mockito 5.4.6 from annotations
// in cribe/test/data/repositories/quizzes/quiz_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i3;

import 'package:cribe/core/logger/logger_mixins.dart' as _i4;
import 'package:cribe/data/models/auth/login_response.dart' as _i7;
import 'package:cribe/data/services/api_service.dart' as _i5;
import 'package:cribe/data/services/storage_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStorageService_0 extends _i1.SmartFake
    implements _i2.StorageService {
  _FakeStorageService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClient_1 extends _i1.SmartFake implements _i3.HttpClient {
  _FakeHttpClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContextualLogger_2 extends _i1.SmartFake
    implements _i4.ContextualLogger {
  _FakeContextualLogger_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_3<T1> extends _i1.SmartFake
    implements _i5.ApiResponse<T1> {
  _FakeApiResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StorageService get storageService => (super.noSuchMethod(
        Invocation.getter(#storageService),
        returnValue: _FakeStorageService_0(
          this,
          Invocation.getter(#storageService),
        ),
      ) as _i2.StorageService);

  @override
  _i3.HttpClient get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeHttpClient_1(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i3.HttpClient);

  @override
  _i4.ContextualLogger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeContextualLogger_2(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i4.ContextualLogger);

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  dynamic updateBaseUrl(String? newUrl) => super.noSuchMethod(Invocation.method(
        #updateBaseUrl,
        [newUrl],
      ));

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setTokens(_i7.LoginResponse? tokens) => (super.noSuchMethod(
        Invocation.method(
          #setTokens,
          [tokens],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  dynamic getStream<T>(
    String? path,
    T Function(
      String,
      Map<String, dynamic>,
    )? fromJson,
  ) =>
      super.noSuchMethod(Invocation.method(
        #getStream,
        [
          path,
          fromJson,
        ],
      ));

  @override
  _i6.Future<_i5.ApiResponse<T>> get<T>(
    String? path,
    T Function(dynamic)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            path,
            fromJson,
          ],
        ),
        returnValue: _i6.Future<_i5.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #get,
            [
              path,
              fromJson,
            ],
          ),
        )),
      ) as _i6.Future<_i5.ApiResponse<T>>);

  @override
  _i6.Future<_i5.ApiResponse<T>> post<T>(
    String? path,
    T Function(dynamic)? fromJson, {
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            path,
            fromJson,
          ],
          {#body: body},
        ),
        returnValue: _i6.Future<_i5.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #post,
            [
              path,
              fromJson,
            ],
            {#body: body},
          ),
        )),
      ) as _i6.Future<_i5.ApiResponse<T>>);

  @override
  _i6.Future<_i5.ApiResponse<T>> delete<T>(
    String? path,
    T Function(dynamic)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            path,
            fromJson,
          ],
        ),
        returnValue: _i6.Future<_i5.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #delete,
            [
              path,
              fromJson,
            ],
          ),
        )),
      ) as _i6.Future<_i5.ApiResponse<T>>);

  @override
  _i6.Future<_i5.ApiResponse<T>> put<T>(
    String? path,
    T Function(dynamic)? fromJson, {
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            path,
            fromJson,
          ],
          {#body: body},
        ),
        returnValue: _i6.Future<_i5.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #put,
            [
              path,
              fromJson,
            ],
            {#body: body},
          ),
        )),
      ) as _i6.Future<_i5.ApiResponse<T>>);

  @override
  _i6.Future<_i5.ApiResponse<T>> patch<T>(
    String? path,
    T Function(dynamic)? fromJson, {
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [
            path,
            fromJson,
          ],
          {#body: body},
        ),
        returnValue: _i6.Future<_i5.ApiResponse<T>>.value(_FakeApiResponse_3<T>(
          this,
          Invocation.method(
            #patch,
            [
              path,
              fromJson,
            ],
            {#body: body},
          ),
        )),
      ) as _i6.Future<_i5.ApiResponse<T>>);
}
