// Mocks generated by Mockito 5.4.6 from annotations
// in cribe/test/data/services/quiz_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:cribe/core/logger/logger_mixins.dart' as _i2;
import 'package:cribe/data/models/quiz/quiz_session.dart' as _i5;
import 'package:cribe/data/models/quiz/quiz_session_detail.dart' as _i3;
import 'package:cribe/data/models/quiz/submit_answer_request.dart' as _i8;
import 'package:cribe/data/models/quiz/user_answer.dart' as _i4;
import 'package:cribe/data/repositories/quizzes/quiz_repository.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContextualLogger_0 extends _i1.SmartFake
    implements _i2.ContextualLogger {
  _FakeContextualLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuizSessionDetailDto_1 extends _i1.SmartFake
    implements _i3.QuizSessionDetailDto {
  _FakeQuizSessionDetailDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserAnswerDto_2 extends _i1.SmartFake implements _i4.UserAnswerDto {
  _FakeUserAnswerDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuizSessionDto_3 extends _i1.SmartFake
    implements _i5.QuizSessionDto {
  _FakeQuizSessionDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuizRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizRepository extends _i1.Mock implements _i6.QuizRepository {
  MockQuizRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ContextualLogger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeContextualLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.ContextualLogger);

  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.QuizSessionDetailDto> getOrCreateSession(int? episodeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateSession,
          [episodeId],
        ),
        returnValue: _i7.Future<_i3.QuizSessionDetailDto>.value(
            _FakeQuizSessionDetailDto_1(
          this,
          Invocation.method(
            #getOrCreateSession,
            [episodeId],
          ),
        )),
      ) as _i7.Future<_i3.QuizSessionDetailDto>);

  @override
  _i7.Future<_i3.QuizSessionDetailDto> getSessionDetail(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionDetail,
          [sessionId],
        ),
        returnValue: _i7.Future<_i3.QuizSessionDetailDto>.value(
            _FakeQuizSessionDetailDto_1(
          this,
          Invocation.method(
            #getSessionDetail,
            [sessionId],
          ),
        )),
      ) as _i7.Future<_i3.QuizSessionDetailDto>);

  @override
  _i7.Future<List<_i3.QuizSessionDetailDto>> getUserSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSessions,
          [],
        ),
        returnValue: _i7.Future<List<_i3.QuizSessionDetailDto>>.value(
            <_i3.QuizSessionDetailDto>[]),
      ) as _i7.Future<List<_i3.QuizSessionDetailDto>>);

  @override
  _i7.Future<_i4.UserAnswerDto> submitAnswer({
    required int? sessionId,
    required _i8.SubmitAnswerRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitAnswer,
          [],
          {
            #sessionId: sessionId,
            #request: request,
          },
        ),
        returnValue: _i7.Future<_i4.UserAnswerDto>.value(_FakeUserAnswerDto_2(
          this,
          Invocation.method(
            #submitAnswer,
            [],
            {
              #sessionId: sessionId,
              #request: request,
            },
          ),
        )),
      ) as _i7.Future<_i4.UserAnswerDto>);

  @override
  _i7.Future<_i5.QuizSessionDto> completeQuiz(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeQuiz,
          [sessionId],
        ),
        returnValue: _i7.Future<_i5.QuizSessionDto>.value(_FakeQuizSessionDto_3(
          this,
          Invocation.method(
            #completeQuiz,
            [sessionId],
          ),
        )),
      ) as _i7.Future<_i5.QuizSessionDto>);
}
