// Mocks generated by Mockito 5.4.6 from annotations
// in cribe/test/ui/quiz/widgets/quiz_sessions_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cribe/core/logger/logger_mixins.dart' as _i2;
import 'package:cribe/data/models/quiz/quiz_session_detail.dart' as _i6;
import 'package:cribe/data/services/quiz_service.dart' as _i4;
import 'package:cribe/domain/models/quiz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContextualLogger_0 extends _i1.SmartFake
    implements _i2.ContextualLogger {
  _FakeContextualLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuizData_1 extends _i1.SmartFake implements _i3.QuizData {
  _FakeQuizData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserAnswer_2 extends _i1.SmartFake implements _i3.UserAnswer {
  _FakeUserAnswer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuizSession_3 extends _i1.SmartFake implements _i3.QuizSession {
  _FakeQuizSession_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuizService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizService extends _i1.Mock implements _i4.QuizService {
  MockQuizService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ContextualLogger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeContextualLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.ContextualLogger);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.QuizData> startQuiz(int? episodeId) => (super.noSuchMethod(
        Invocation.method(
          #startQuiz,
          [episodeId],
        ),
        returnValue: _i5.Future<_i3.QuizData>.value(_FakeQuizData_1(
          this,
          Invocation.method(
            #startQuiz,
            [episodeId],
          ),
        )),
      ) as _i5.Future<_i3.QuizData>);

  @override
  _i5.Future<_i3.QuizData> getSessionDetail(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionDetail,
          [sessionId],
        ),
        returnValue: _i5.Future<_i3.QuizData>.value(_FakeQuizData_1(
          this,
          Invocation.method(
            #getSessionDetail,
            [sessionId],
          ),
        )),
      ) as _i5.Future<_i3.QuizData>);

  @override
  _i5.Future<List<_i6.QuizSessionDetailDto>> getUserSessions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSessions,
          [],
        ),
        returnValue: _i5.Future<List<_i6.QuizSessionDetailDto>>.value(
            <_i6.QuizSessionDetailDto>[]),
      ) as _i5.Future<List<_i6.QuizSessionDetailDto>>);

  @override
  _i5.Future<List<_i3.QuizData>> getUserQuizSessions() => (super.noSuchMethod(
        Invocation.method(
          #getUserQuizSessions,
          [],
        ),
        returnValue: _i5.Future<List<_i3.QuizData>>.value(<_i3.QuizData>[]),
      ) as _i5.Future<List<_i3.QuizData>>);

  @override
  _i5.Future<_i3.UserAnswer> submitAnswer({
    required int? sessionId,
    required int? questionId,
    int? selectedOptionId,
    String? textAnswer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitAnswer,
          [],
          {
            #sessionId: sessionId,
            #questionId: questionId,
            #selectedOptionId: selectedOptionId,
            #textAnswer: textAnswer,
          },
        ),
        returnValue: _i5.Future<_i3.UserAnswer>.value(_FakeUserAnswer_2(
          this,
          Invocation.method(
            #submitAnswer,
            [],
            {
              #sessionId: sessionId,
              #questionId: questionId,
              #selectedOptionId: selectedOptionId,
              #textAnswer: textAnswer,
            },
          ),
        )),
      ) as _i5.Future<_i3.UserAnswer>);

  @override
  _i5.Future<_i3.QuizSession> completeQuiz(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeQuiz,
          [sessionId],
        ),
        returnValue: _i5.Future<_i3.QuizSession>.value(_FakeQuizSession_3(
          this,
          Invocation.method(
            #completeQuiz,
            [sessionId],
          ),
        )),
      ) as _i5.Future<_i3.QuizSession>);
}
